CCBAG_NAME_BAG = "Backpack"
CCBAG_NAME_MOUNT = "Mount Tracker"
CCBAG_NAME_PET = "iPet"
CCBAG_NAME_TOY = "Toypal"
CCBAG_NAME_SET = "Sticker Book"


BINDING_NAME_TOGGLEBACKPACK = "Toggle "..CCBAG_NAME_BAG;
BINDING_NAME_TOGGLEBAG1 = "Toggle "..CCBAG_NAME_MOUNT;
BINDING_NAME_TOGGLEBAG2 = "Toggle "..CCBAG_NAME_PET;
BINDING_NAME_TOGGLEBAG3 = "Toggle "..CCBAG_NAME_TOY;
BINDING_NAME_TOGGLEBAG4 = "Toggle Unreleased Container";
BINDING_NAME_TOGGLEBAG4 = "Toggle Unreleased Container";

BINDING_HEADER_CCBAGS = "Container Slots";

BINDING_NAME_USEBAG1 = CCBAG_NAME_BAG.." Slot 1";
BINDING_NAME_USEBAG2 = CCBAG_NAME_BAG.." Slot 2";
BINDING_NAME_USEBAG3 = CCBAG_NAME_BAG.." Slot 3";
BINDING_NAME_USEBAG4 = CCBAG_NAME_BAG.." Slot 4";
BINDING_NAME_USEBAG5 = CCBAG_NAME_BAG.." Slot 5";
BINDING_NAME_USEBAG6 = CCBAG_NAME_BAG.." Slot 6";
BINDING_NAME_USEBAG7 = CCBAG_NAME_BAG.." Slot 7";
BINDING_NAME_USEBAG8 = CCBAG_NAME_BAG.." Slot 8";
BINDING_NAME_USEBAG9 = CCBAG_NAME_BAG.." Slot 9";
BINDING_NAME_USEBAG10 = CCBAG_NAME_BAG.." Slot 10";
BINDING_NAME_USEBAG11 = CCBAG_NAME_BAG.." Slot 11";
BINDING_NAME_USEBAG12 = CCBAG_NAME_BAG.." Slot 12";
BINDING_NAME_USEBAG13 = CCBAG_NAME_BAG.." Slot 13";
BINDING_NAME_USEBAG14 = CCBAG_NAME_BAG.." Slot 14";
BINDING_NAME_USEBAG15 = CCBAG_NAME_BAG.." Slot 15";
BINDING_NAME_USEBAG16 = CCBAG_NAME_BAG.." Slot 16";

BINDING_NAME_USEMOUNT1 = CCBAG_NAME_MOUNT.." Slot 1";
BINDING_NAME_USEMOUNT2 = CCBAG_NAME_MOUNT.." Slot 2";
BINDING_NAME_USEMOUNT3 = CCBAG_NAME_MOUNT.." Slot 3";
BINDING_NAME_USEMOUNT4 = CCBAG_NAME_MOUNT.." Slot 4";
BINDING_NAME_USEMOUNT5 = CCBAG_NAME_MOUNT.." Slot 5";
BINDING_NAME_USEMOUNT6 = CCBAG_NAME_MOUNT.." Slot 6";

BINDING_NAME_USEPET1 = CCBAG_NAME_PET.." Slot 1";
BINDING_NAME_USEPET2 = CCBAG_NAME_PET.." Slot 2";
BINDING_NAME_USEPET3 = CCBAG_NAME_PET.." Slot 3";

BINDING_NAME_USETOY1 = CCBAG_NAME_TOY.." Slot 1";
BINDING_NAME_USETOY2 = CCBAG_NAME_TOY.." Slot 2";
BINDING_NAME_USETOY3 = CCBAG_NAME_TOY.." Slot 3";
BINDING_NAME_USETOY4 = CCBAG_NAME_TOY.." Slot 4";
BINDING_NAME_USETOY5 = CCBAG_NAME_TOY.." Slot 5";
BINDING_NAME_USETOY6 = CCBAG_NAME_TOY.." Slot 6";

