CCBAG_NAME_BAG = "BACKPACK"
CCBAG_NAME_PET = "PET PEN"
CCBAG_NAME_TOY = "TOYPAD"
CCBAG_NAME_SET = "SET BUILDER"
CCBAG_NAME_MOUNT = "MOUNT LEASH"



BINDING_NAME_TOGGLEBACKPACK = "Toggle Backpack";
BINDING_NAME_TOGGLEBAG1 = "Toggle Mount Container";
BINDING_NAME_TOGGLEBAG2 = "Toggle Pet Container";
BINDING_NAME_TOGGLEBAG3 = "Toggle Toybox";
BINDING_NAME_TOGGLEBAG4 = "Toggle Unreleased Container";
BINDING_NAME_TOGGLEBAG4 = "Toggle Unreleased Container";

BINDING_HEADER_CCBAGS = "Container Slots";

BINDING_NAME_USEBAG1 = "Backpack Slot 1";
BINDING_NAME_USEBAG2 = "Backpack Slot 2";
BINDING_NAME_USEBAG3 = "Backpack Slot 3";
BINDING_NAME_USEBAG4 = "Backpack Slot 4";
BINDING_NAME_USEBAG5 = "Backpack Slot 5";
BINDING_NAME_USEBAG6 = "Backpack Slot 6";
BINDING_NAME_USEBAG7 = "Backpack Slot 7";
BINDING_NAME_USEBAG8 = "Backpack Slot 8";
BINDING_NAME_USEBAG9 = "Backpack Slot 9";
BINDING_NAME_USEBAG10 = "Backpack Slot 10";
BINDING_NAME_USEBAG11 = "Backpack Slot 11";
BINDING_NAME_USEBAG12 = "Backpack Slot 12";
BINDING_NAME_USEBAG13 = "Backpack Slot 13";
BINDING_NAME_USEBAG14 = "Backpack Slot 14";
BINDING_NAME_USEBAG15 = "Backpack Slot 15";
BINDING_NAME_USEBAG16 = "Backpack Slot 16";

BINDING_NAME_USEMOUNT1 = "Mount Bar Slot 1";
BINDING_NAME_USEMOUNT2 = "Mount Bar Slot 2";
BINDING_NAME_USEMOUNT3 = "Mount Bar Slot 3";
BINDING_NAME_USEMOUNT4 = "Mount Bar Slot 4";
BINDING_NAME_USEMOUNT5 = "Mount Bar Slot 5";
BINDING_NAME_USEMOUNT6 = "Mount Bar Slot 6";

BINDING_NAME_USEPET1 = "Pet Bag Slot 1";
BINDING_NAME_USEPET2 = "Pet Bag Slot 2";
BINDING_NAME_USEPET3 = "Pet Bag Slot 3";

BINDING_NAME_USETOY1 = "Toy Container Slot 1";
BINDING_NAME_USETOY2 = "Toy Container Slot 2";
BINDING_NAME_USETOY3 = "Toy Container Slot 3";
BINDING_NAME_USETOY4 = "Toy Container Slot 4";
BINDING_NAME_USETOY5 = "Toy Container Slot 5";
BINDING_NAME_USETOY6 = "Toy Container Slot 6";

